name: CD
on:
  push:
    branches:
      - main

jobs:
  release-version:
    name: Release a version
    runs-on: ubuntu-22.04

    steps:
      - name: Release Fish script
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: Argument handler
          files: |
            *.fish
            README.md
