name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  check-scripts:
    name: Check scripts
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Fish shell
        uses: fish-actions/install-fish@v1.1.0
      - name: Check Fish scripts
        run: fish --no-execute *.fish
