name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  check-scripts:
    name: Check scripts
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Fish scripts
        run: fish --no-execute *.fish
